Hw 5 read file
mate-academy/jv-read-from-file pull request #193
Opened 2021-04-01 19:27 UTC by IhorRome

2021-04-02 08:10 UTC, Resci requested changes

2021-04-02 08:10 UTC, Resci commented on src/main/java/core/basesyntax/FileWork.java
> +            }
Too complex if-else constructions, let's simplify

2021-04-02 15:56 UTC, KseniiaMakarova requested changes

2021-04-02 15:56 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FileWork.java
> +            int value = reader.read();
let's use `readLine()` instead - what do you think?

2021-04-02 15:56 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FileWork.java
> +                if (Character.toLowerCase((char)value) == SPECIFIED_CHARACTER) {
use startsWith() instead

2021-04-02 15:56 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FileWork.java
> +    public String [] toStringArray(StringBuilder builder) {
let's make the helper methods private

2021-04-02 15:56 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FileWork.java
> +            String [] result = builder.toString().split(" ");
```suggestion
            String[] result = builder.toString().split(" ");
```

2021-04-02 15:56 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FileWork.java
> +            return new String[] {};
```suggestion
            return new String[0];
```

2021-04-05 08:55 UTC, Sofasmile requested changes

2021-04-05 08:55 UTC, Sofasmile commented on src/main/java/core/basesyntax/FileWork.java
> +            throw new RuntimeException("can't read from file");
```suggestion
            throw new RuntimeException("can't read from file", e);
```

2021-04-05 08:55 UTC, Sofasmile commented on src/main/java/core/basesyntax/FileWork.java
> +                .toLowerCase(Locale.ROOT);
we cam simplify to toLowerCase()

2021-04-05 08:55 UTC, Sofasmile commented on src/main/java/core/basesyntax/FileWork.java
> +                builder.append(word);
```suggestion
                builder.append(word).append(' ');
```

2021-04-05 08:55 UTC, Sofasmile commented on src/main/java/core/basesyntax/FileWork.java
> +            String[] result = builder.toString().split(" ");
```suggestion
            String[] result = builder.toString().trim().split(" ");
```

2021-04-05 08:55 UTC, Sofasmile commented on src/main/java/core/basesyntax/FileWork.java
> +        } else {
do we need else after return statement?

2021-04-05 14:48 UTC, Sofasmile approved these changes

2024-10-14 09:13 UTC, closed without merging